name: simple_filepicker_windows
description: simple filepicker plugin for windows without any dependencies(hopefully)
version: 1.0.0+8
homepage: "https://github.com/giorgionegro/flutter_filepicker_windows"
repository: "https://github.com/giorgionegro/flutter_filepicker_windows"
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SimpleFilepickerWindowsPluginCApi
